// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: gRPC/interface.proto

package auction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionClient is the client API for Auction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionClient interface {
	Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*ClientReply, error)
	Result(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ClientReply, error)
	Reset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ClientReply, error)
	ServerBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*OutcomeReply, error)
	ServerResult(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResultReply, error)
	ServerReset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*OutcomeReply, error)
}

type auctionClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionClient(cc grpc.ClientConnInterface) AuctionClient {
	return &auctionClient{cc}
}

func (c *auctionClient) Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*ClientReply, error) {
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionClient) Result(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ClientReply, error) {
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionClient) Reset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ClientReply, error) {
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionClient) ServerBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*OutcomeReply, error) {
	out := new(OutcomeReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/serverBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionClient) ServerResult(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResultReply, error) {
	out := new(ResultReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/serverResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionClient) ServerReset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*OutcomeReply, error) {
	out := new(OutcomeReply)
	err := c.cc.Invoke(ctx, "/auction.Auction/ServerReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionServer is the server API for Auction service.
// All implementations must embed UnimplementedAuctionServer
// for forward compatibility
type AuctionServer interface {
	Bid(context.Context, *BidRequest) (*ClientReply, error)
	Result(context.Context, *Request) (*ClientReply, error)
	Reset(context.Context, *Request) (*ClientReply, error)
	ServerBid(context.Context, *BidRequest) (*OutcomeReply, error)
	ServerResult(context.Context, *Request) (*ResultReply, error)
	ServerReset(context.Context, *Request) (*OutcomeReply, error)
	mustEmbedUnimplementedAuctionServer()
}

// UnimplementedAuctionServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionServer struct {
}

func (UnimplementedAuctionServer) Bid(context.Context, *BidRequest) (*ClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionServer) Result(context.Context, *Request) (*ClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionServer) Reset(context.Context, *Request) (*ClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedAuctionServer) ServerBid(context.Context, *BidRequest) (*OutcomeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerBid not implemented")
}
func (UnimplementedAuctionServer) ServerResult(context.Context, *Request) (*ResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerResult not implemented")
}
func (UnimplementedAuctionServer) ServerReset(context.Context, *Request) (*OutcomeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerReset not implemented")
}
func (UnimplementedAuctionServer) mustEmbedUnimplementedAuctionServer() {}

// UnsafeAuctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServer will
// result in compilation errors.
type UnsafeAuctionServer interface {
	mustEmbedUnimplementedAuctionServer()
}

func RegisterAuctionServer(s grpc.ServiceRegistrar, srv AuctionServer) {
	s.RegisterService(&Auction_ServiceDesc, srv)
}

func _Auction_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).Bid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auction_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).Result(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auction_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).Reset(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auction_ServerBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).ServerBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/serverBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).ServerBid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auction_ServerResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).ServerResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/serverResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).ServerResult(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auction_ServerReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).ServerReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.Auction/ServerReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).ServerReset(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Auction_ServiceDesc is the grpc.ServiceDesc for Auction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auction.Auction",
	HandlerType: (*AuctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "bid",
			Handler:    _Auction_Bid_Handler,
		},
		{
			MethodName: "result",
			Handler:    _Auction_Result_Handler,
		},
		{
			MethodName: "reset",
			Handler:    _Auction_Reset_Handler,
		},
		{
			MethodName: "serverBid",
			Handler:    _Auction_ServerBid_Handler,
		},
		{
			MethodName: "serverResult",
			Handler:    _Auction_ServerResult_Handler,
		},
		{
			MethodName: "ServerReset",
			Handler:    _Auction_ServerReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/interface.proto",
}
